# Baixados {#baixados}

## Do Processamento Final

Nesta etapa, ocorre a baixa do processo, que é o marco final da tramitação e representa o momento em que se encerram todas as atividades (jurisdicionais e cartorárias) do processo no âmbito do STF.

Este é o ato que marca o momento em que todas as determinações constantes na sentença foram cumpridas pelas partes litigantes. Pode promover o arquivamento do processo ou remessa para outro juízo ou tribunal.

É seguido de atividades cartorárias, como registro da baixa definitiva do processo pelo serviço de distribuição e a respectiva exclusão do nome das partes nas certidões judiciais de distribuição.

Esta etapa embora correlacionada, não se confunde com o **Trânsito em Julgado**. Esse é o momento no qual não cabe mais recurso, seja ordinário ou extraordinário. Na prática, trata-se um adjetivo aplicado a uma decisão que não pode sofrer reforma, ou seja, que não pode mais ser modificada.

## Regra de Baixa

A quantidade de processos baixados corresponde ao total de processos distintos fora de tramitação na data da execução do relatório, que tenham a data da baixa no ano de referência. O ministro responsável pela baixa será registrado como o **relator do último incidente**.

>Pergunta: é isso mesmo? Relator do último andamento ou relator do último incidente? [STI]

A Data da Baixa corresponde à data do primeiro andamento que retirou o processo de tramitação e que, após este andamento não ocorreu lançamento de andamento em que o processo voltasse a tramitar.

>Pergunta:  todos esses movimentos dão baixa a um processo ou só retiram de trâmite? [STI]

**Andamentos que retiram um processo de trâmite**

```{r echo=FALSE, message=FALSE, warning=FALSE, include = TRUE, fig.showtext = TRUE, error=FALSE}
library(readxl)
library(dplyr)
library(tidyverse)
library(stringi)
library(showtext)
tabela_1_baixados = read_excel("dados/tabela_1_baixados.xlsx")
tabela_1_baixados %>%
    knitr::kable(align = "l") %>% 
    kableExtra::kable_styling(full_width = F,latex_options = "HOLD_position",font_size = 14)
```

## Painel de Baixados

O painel de processos é o mesmo do painel de processos recebidos. Ver [aqui](https://euleralencar.gitbook.io/glossario-estatistico-bk_2021_11_26/dimensoes/recebimento/painel-de-recebimento).