# Perguntas frequentes (FAQ)

**Consigo obter dados de 1988 até hoje?**

> Os dados anteriores a 2000 não são precisos. O STF começou pelo processo de digitalização em 1996 e somente a partir de 2000 as bases foram complemente registradas em bases de dados estruturadas e informatizadas. Isso siginfica que processos autuados a partir de 2000 estão completamente registrados na base de dados e processos que estavam em tramitação nesse ano também foram incluídos nas bases digitais. 

<mark>Verificar com STI sobre o histórico dessa questão.</mark>

**Como obter dados de 1988 até 2000?**

<mark>Sem resposta.</mark>

**Posso baixar os dados de acervo?**

> Sim. É possível baixar os dados de acervo em um arquivo que é atualizado diariamente, dados de acervo recursais e originários. Além disso, é possível baixa a listagem de processos recebidos e baixados no ano.

> Relação de base dados [aqui](http://portal.stf.jus.br/textos/verTexto.asp?servico=estatistica&pagina=acervoatual).^[Dados atualizados diariamente. Não há possibilidade de resgate do histórico.]

**Como posso fazer uma pesquisa de Amicus Curie?**

<mark>Como fazer uma pesquisa nas partes dos processos em tramitação (acervo)?</mark>

**Como são elaboradas as páginas e relatórios estatísticos?**

> Os relatórios são elaborados a partir de consultas à base de dados do Tribunal. A consulta é construída a partir de parâmetros lógicos e o resultado é apresentado sem interferência humana. Ou seja, os dados são apresentados da mesma forma como estão registrados na base de dados. 

**Qual é a freqüência de atualização das páginas da estatística?**

> As páginas da estatística referentes ao acervo, às decisões, à pauta do Plenário e à competência recursal divulgadas no Portal do STF são atualizadas diariamente, de forma automática, e trazem os dados do dia anterior. As demais páginas são atualizadas mensalmente pela Assessoria de Gestão Estratégica e trazem as informações referentes ao fechamento do mês anterior. 

**Como é determinada a situação de um processo?**

> Como as consultas são feitas automaticamente, a situação de um processo é determinada a partir de parâmetros lógicos, baseados nos dados disponíveis. Embora ainda haja inconsistências, a base de dados do Tribunal permite, atualmente, um grau razoável de precisão nessa identificação. Para saber em que situação se encontra um processo, é necessário definir quais dados a determinam, bem como aqueles que a excluem.  Por exemplo, os processos que estão na pauta aguardando julgamento - situação "Em mesa/pauta" - são aqueles que possuem um andamento que indique a inclusão na pauta e que não possuem andamento posterior a esse que indique decisão colegiada.  
Os erros na identificação da situação do processo podem ser resultado de:  <br> 1. inadequação dos parâmetros de consulta definidos; <br> 2.
falha na aplicação dos parâmetros pelo sistema de estatística; <br> 3. falha no registro dos dados (ex.: o processo não possui andamento de inclusão em pauta, mas andamento de despacho que, em seu teor, contém determinação de inclusão em pauta. O sistema não e capaz de 'ler' o despacho, mas somente os dados lançados em sistema. Nesse caso, o processo está em pauta, mas os relatórios estatísticos não conseguirão identificar essa situação).

